### ISSUE TITLE
游戏流程

### ISSUE THREAD

**Issue by yfzm** [yfzm/poker-bot#54]
- [x] 任何人都可以开始一局游戏
- [ ] 任何人都可以在任意时刻加入一张桌子（但是需要等待下一局）
- [ ] 任何人都可以在任意时刻退出一张桌子（当前局视为fold）
- [ ] 桌子可以在以下情况下被解散：
    1. open后2min内没有start
    2. 游戏人数只剩一个人（最好此时进入2min倒计时）
    3. 至少两人同时同意解散一张桌子（比如有人没有显式退出，却一直在牌桌上，影响游戏体验）

**Comment by laazy** [comment]
游戏中途解散的功能可以留到下次再做。
游戏人数只剩一个人的情况可以这么处理：每轮游戏开始前判断人数，若人数少于一人（或两人）直接结束当前桌子。
