### ISSUE TITLE
游戏结束时展示手牌

### ISSUE THREAD

**Issue by yfzm** [yfzm/poker-bot#73]
规则如下：
- 只剩下一个人时不需要展示手牌
- 剩下多人时，展示牌的顺序从河牌圈的激进者(首先下注或加注者，都check则为第一个行动者)开始依次往后，如果待展示的手牌比之前展示的所有手牌都大，则亮出该手牌；否则不亮牌
- 在河牌圈之前所有玩家all-in，所有人都需要展示手牌

**Comment by laazy** [comment]
如果不比之前的大，应该也要给玩家选择是否亮手牌吧。

**Comment by yfzm** [comment]
@laazy 那不是游戏规则的一部分，实在想说出去，可以通过聊天窗口打出来

**Comment by Veiasai** [comment]
感觉可以=，=
