### ISSUE TITLE
添加close和reopen指令

### ISSUE THREAD

**Issue by yfzm** [yfzm/poker-bot#84]
close：关闭一个牌桌
reopen：重开本牌桌

**Comment by laazy** [comment]
能否让牌桌这个东西简单一点，或者说去除牌桌在游戏中的存在感。
让start就是开始游戏，若无牌桌则创建，游戏结束后随时可以加入。当一场游戏结束超过一段时间，自动关闭牌桌。
这样的话可以省掉open、close、reopen等命令。
关于游戏状态管理的命令只需要start、join、leave就可以了。

**Comment by laazy** [comment]
加一个restart来重新开启游戏
